// Generated by gencpp from file dynamixel_workbench_msgs/WheelCommand.msg
// DO NOT EDIT!


#ifndef DYNAMIXEL_WORKBENCH_MSGS_MESSAGE_SWERVEDRIVECOMMAND_H
#define DYNAMIXEL_WORKBENCH_MSGS_MESSAGE_SWERVEDRIVECOMMAND_H

#include <ros/service_traits.h>


#include "SwerveDriveCommandRequest.h"
#include "SwerveDriveCommandResponse.h"


namespace dynamixel_workbench_msgs
{

struct SwerveDriveCommand
{

typedef SwerveDriveCommandRequest Request;
typedef SwerveDriveCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct WheelCommand
} // namespace dynamixel_workbench_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::dynamixel_workbench_msgs::SwerveDriveCommand > {
  static const char* value()
  {
    return "a7851f940124222501142592f81f3c11";
  }

  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommand&) { return value(); }
};

template<>
struct DataType< ::dynamixel_workbench_msgs::SwerveDriveCommand > {
  static const char* value()
  {
    return "dynamixel_workbench_msgs/SwerveDriveCommand";
  }

  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommand&) { return value(); }
};


// service_traits::MD5Sum< ::dynamixel_workbench_msgs::WheelCommandRequest> should match 
// service_traits::MD5Sum< ::dynamixel_workbench_msgs::WheelCommand > 
template<>
struct MD5Sum< ::dynamixel_workbench_msgs::SwerveDriveCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_workbench_msgs::SwerveDriveCommand >::value();
  }
  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_workbench_msgs::WheelCommandRequest> should match 
// service_traits::DataType< ::dynamixel_workbench_msgs::WheelCommand > 
template<>
struct DataType< ::dynamixel_workbench_msgs::SwerveDriveCommandRequest>
{
  static const char* value()
  {
    return DataType< ::dynamixel_workbench_msgs::SwerveDriveCommand >::value();
  }
  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::dynamixel_workbench_msgs::WheelCommandResponse> should match 
// service_traits::MD5Sum< ::dynamixel_workbench_msgs::WheelCommand > 
template<>
struct MD5Sum< ::dynamixel_workbench_msgs::SwerveDriveCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::dynamixel_workbench_msgs::SwerveDriveCommand >::value();
  }
  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::dynamixel_workbench_msgs::WheelCommandResponse> should match 
// service_traits::DataType< ::dynamixel_workbench_msgs::WheelCommand > 
template<>
struct DataType< ::dynamixel_workbench_msgs::SwerveDriveCommandResponse>
{
  static const char* value()
  {
    return DataType< ::dynamixel_workbench_msgs::SwerveDriveCommand >::value();
  }
  static const char* value(const ::dynamixel_workbench_msgs::SwerveDriveCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DYNAMIXEL_WORKBENCH_MSGS_MESSAGE_WHEELCOMMAND_H
